### ISSUE TITLE
XML with DOCTYPE declaration rejected by xml2hash

### ISSUE THREAD

**Issue by nigelm** [yoreek/XML-Hash-XS#11]
An XML file with a `<!DOCTYPE ...>` declaration is rejected with the error 'Invalid XML'.

A sample XML file that I am attempting to parse is attached (extension changed to txt due to GitHub restrictions)
[min.txt](https://github.com/yoreek/XML-Hash-XS/files/1122214/min.txt)
.

**Comment by yoreek** [comment]
Thanks for being interested.
This feature is not implemented yet, I need to find some free time to do it.

**Comment by yoreek** [comment]
I implemented the parser for DTD, but with partial support, because full support too complex.
The parser will only skip DTD block, perhaps this will be enough.
