### ISSUE TITLE
empty hash keys result in invalid xml

### ISSUE THREAD

**Issue by sezal** [yoreek/XML-Hash-XS#13]
Serialization of hash with empty keys produces invalid XML. Consider switching to XML::Simple's approach, because it safer (produces valid XML).

```
use XML::Simple;
use XML::Hash::XS;

say hash2xml ({foo => 'FOO', '' => 'x'}, indent => 1, xml_decl => 0);
say XMLout ({foo => 'FOO', '' => 'x'}, NoAttr => 1);
```

```
<root>
 <>x</>
 <foo>FOO</foo>
</root>

<opt>
x
  <foo>FOO</foo>
</opt>
```

**Comment by yoreek** [comment]
In XML::Simple its own logic and it is not always correct in all cases, for example:
```
$ perl -e "use XML::Simple;print XMLout({'' => 'x'})"
<opt ="x" />

$ perl -e "use XML::Simple;print XMLout({'' => ['x', 'y']}, NoAttr => 1)"
<opt>
  <>x</>
  <>y</>
</opt>
```
I think it's better to replace empty tags with a line like "_" or something else customizable, for example:
```
<opt "_"="x" />
<opt>
  <_>x</_>
  <_>y</_>
</opt>
```

**Comment by sezal** [comment]
I see. You probably right. Any solution that results in valid XML is already step forward.
Btw, attribute name in you example probably should be unquoted.

**Comment by yoreek** [comment]
outdated
