### ISSUE TITLE
Option for rootless xml

### ISSUE THREAD

**Issue by sezal** [yoreek/XML-Hash-XS#14]
```
$ perl -e "use XML::Hash::XS; print hash2xml {'x' => ['x', 'y']}, xml_decl => 0, keep_root => 0;"
<root><x>x</x><x>y</x></root>

$ perl -e "use XML::Hash::XS; print hash2xml {'x' => ['x', 'y']}, xml_decl => 0, keep_root => 1;"
<root><x>x</x><x>y</x></root>

$ perl -e "use XML::Hash::XS; print hash2xml {'x' => ['x', 'y']}, xml_decl => 0, root => undef;"
<><x>x</x><x>y</x></>
```
but

```
perl -e "use XML::Simple; print XMLout({'x' => ['x', 'y']}, NoAttr => 1, KeepRoot => 0)"
<opt>
  <x>x</x>
  <x>y</x>
</opt>

$ perl -e "use XML::Simple; print XMLout({'x' => ['x', 'y']}, NoAttr => 1, KeepRoot => 1)"
<x>x</x>
<x>y</x>
```
I'd expect KeepRoot => 0 to eliminate root, but even though it's badly named (IMHO) and does opposite there is a way.

It would be nice to have such option in your module as well.
I'd tend more to root => undef and leave keep_root for decoding only to avoid confusion, but you may want it to be more consistent XML::Simple.

**Comment by yoreek** [comment]
1. The parameter "keep_root" is used only to convert "hml2hash".
2. The parameter "root" must be non-empty, because it generates not the correct XML, even keys in the hash must be non-empty.

It is possible that we need a root, for example:
```perl
perl -e "use XML::Simple; print XMLout({'x' => ['x', 'y'], 'x2' => 3}, NoAttr => 1, KeepRoot => 1)"
<opt>
  <x>x</x>
  <x>y</x>
  <x2>3</x2>
</opt>
```
If we want to generate XML without root, then we need to handle somehow the situation when there can be more than one key in the hash.

**Comment by sezal** [comment]
Agree, XML::Simple is bad example and we shouldn't copy their logic. But still it might be useful to support root => undef (or new/dedicated option) case in hash2xml(). It's useful when resulting (big) XML is generated from parts: one part of code responsible for generation of container tag and another part - for actual conversion of hashes. It's not optimal to generate  temporary root (marker) for each hash  and then to get that root to be removed with regexp.

**Comment by yoreek** [comment]
outdated
