### ISSUE TITLE
Support for arbitrary text in RowsIterator::iternext

### ISSUE THREAD

**Issue by sezal** [yoreek/XML-Hash-XS#15]
When generating big XML via RowsIterator::iternext it would be nice to have a way to generate extra data to be appended right after each line. It can be useful in different cases:
1. add comment block associated with a row, e.x. with meta info
```
<row x="1" y="2" /> <!-- x: 1; y: 2 -->
```
2. In combination with indent => 0 it can help to product \n after each line to make document semi-readable. Or more important to force glibc to flush buffer when outputting XML to a socket. Thus receiver can read data in chunks without waiting when entire XML document generated.

I believe the best way to implement this is to return arbitrary text as 2nd argument in 
```
            my $count = 0;
            *RowsIterator::iternext = sub {
                ..........
                return (\%row, "\n") unless $count % 100;
                return \%row;
            };

```

**Comment by yoreek** [comment]
outdated
