### ISSUE TITLE
Elements containing only spaces get automatically trimmed

### ISSUE THREAD

**Issue by marghidanu** [yoreek/XML-Hash-XS#16]
I believe the title is pretty descriptive but it's better to put a little context on it. Right now in our application spaces have meaning and we're actually relying on these values. The trim option set to 0 works fine as long  as the value does not consist only of spaces. Therefor in this situation:
```
<root><tag>    </tag></root>
```
the value for **tag** will be set to empty string. The problem is we cannot differentiate between this and the following XML:
 ```
<root><tag/></root>
```
Thank you!

**Comment by yoreek** [comment]
Thanks for report.
I fixed bug on version 0.53.
Can you check please ?

**Comment by marghidanu** [comment]
Yep! Works just fine, just tested it and staged it in the local Perl repository. Thanks for the bugfix!
