### ISSUE TITLE
Feature Request: `SuppressEmpty => undef` support

### ISSUE THREAD

**Issue by slobo** [yoreek/XML-Hash-XS#17]
Hi,
Thanks for the great work, we love `XML::Hash::XS` and rely on it in production. We've found another opportunity to benefit form the blazing speed of it - by having `Paws` (Perl AWS SDK) switch to `XML::Hash::XS` from `XML::Simple`. 

Work on this has begun, see  pplu/aws-sdk-perl#66 and  pplu/aws-sdk-perl#366. One incompatibility we hit is the configurable `SuppressEmpty` behaviour of `XML::Simple`. Currently, `XML::Hash::XS` behaves equivalent to specifying `SuppressEmpty => ''` -- it produces empty strings when empty nodes (no content and no attribute) is found. For `Paws` purposes, it would be great to have ability to emit `undef` instead, so we don't have to do an additional pass over the resulting hash to remove those, which would negate some of the speed benefits of using `X:H:XS`.  

Is this something that you think is appropriate to be added to `XML::Hash::XS`? `Paws` don't need the other behaviours of `SuppressEmpty` (`XML::Simple` defaults to emitting an empty hash, `1` for skipping empty nodes altogether), but it could perhaps help others migrate if those would be easy to add too. 

Thanks!

**Comment by yoreek** [comment]
Thank you for your interest with this module.
I added the “suppress_empty” option with the same behavior as in XML::Simple, although almost everything is already confused in this module, and need to refactor it.
Please test the module so that everything works as it should.

**Comment by slobo** [comment]
Thank you for such quick response. `suppress_empty => undef` seems to work exactly as we need it!
