### ISSUE TITLE
unable to parse valid xml

### ISSUE THREAD

**Issue by zdm** [yoreek/XML-Hash-XS#18]
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="//css-tricks.com/wp-content/plugins/wordpress-seo-premium/css/main-sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<sitemap>
		<loc>https://css-tricks.com/post-sitemap1.xml</loc>
		<lastmod>2011-12-06T01:22:36+00:00</lastmod>
	</sitemap>
</sitemapindex>
<!-- XML Sitemap generated by Yoast SEO -->

```

The problem in line 2:
```
<?xml-stylesheet type="text/xsl" href="//css-tricks.com/wp-content/plugins/wordpress-seo-premium/css/main-sitemap.xsl"?>
```

**Comment by yoreek** [comment]
I did not even know what this instruction was. It has nothing to do with converting to a hash, and I don’t even know if it needs to be implemented.

**Comment by zdm** [comment]
Hi.

This is valid sitemap.xml file.
Currently it is parsed wit error.
Maybe you need to skip such lines?

**Comment by yoreek** [comment]
Hi!
Fixed in v0.55, check please.

**Comment by zdm** [comment]
thank you
i will test it

**Comment by zdm** [comment]
Something wrong with this fucking cpan.
v0.55 is still not available for install, after day passed.
maybe indexing problems?

**Comment by yoreek** [comment]
Yes!
I got error after upload module:
module : XML::Hash::XS
     version: undef
     in file: XML-Hash-XS-0.55/lib/XML/Hash/XS.pm
     status : The PAUSE indexer could not store the indexing result in
             the DB due the following error: C< Lock wait timeout
             exceeded; try restarting transaction 
I sent bug report but haven’t received a response yet.

**Comment by zdm** [comment]
Do not wait, they will never respond.
You can force reindexing in your PAUSE account.

**Comment by yoreek** [comment]
Reindexed successfully!
