### ISSUE TITLE
content key and indent

### ISSUE THREAD

**Issue by arcanez** [yoreek/XML-Hash-XS#20]
given `$data = { error => { content => 'foo' } }`

using `XML::Simple`: 
```
XMLout($data, RootName => 'result', XMLDecl => '<?xml version="1.0" encoding="utf-8"?>');
```

```
<?xml version="1.0" encoding="utf-8"?>
<result>
  <error>foo</error>
</result>
```
using `XML::Hash::XS`: 
```
hash2xml($data, root => 'result', use_attr => 1, canonical => 1, indent => 2, content => 'content');
```

```
<?xml version="1.0" encoding="utf-8"?>
<result>
  <error>
    foo
  </error>
</result>
```

is it possible to have `XML::Hash::XS` output the same as `XML::Simple` (the `content` value is inline with the tag, rather than a newline and indented)

**Comment by yoreek** [comment]
Unfortunately, indentation currently applies to both tags and content.
