### ISSUE TITLE
Error with parsing xml with url parms

### ISSUE THREAD

**Issue by dkhosla** [yoreek/XML-Hash-XS#21]
Hi,
If the XML is as follows:
```
my $xml = '<root>
  <supportedUrls>
    <url>/xyz/</url>
    <url>/xyz/opt1=&opt2=</url>
  </supportedUrls>
</root>';
```

The entry 
`<url>/xyz/opt1=&opt2=</url>`
 causes a 'Invalid reference' error. 
Also, how to catch any internal error in parsing? It seems to just exit...

**Comment by yoreek** [comment]
You need escape `&` symbol like this `&amp;`

**Comment by dkhosla** [comment]
Thanks Yuriy. Will try.
Is there a way to catch an error in parsing vs. just exiting the whole program from within the package? I did not see any documentation on error handling..

Regards,
Deepak Khosla
Office: 832-280-5038

**Comment by yoreek** [comment]
You can use `eval` function:
```
eval { ... };

if ($@) { ... };

```

**Comment by dkhosla** [comment]
Thanks. I may have missed the fix but putting single quotes around the & does not work. Fails. (Works if I remove the '&' line). 

my $xml = "<root>
  <supportedUrls>
    <url>/xyz/</url>
    <url>/xyz/opt1='&'opt2=</url>
  </supportedUrls>
</root>";

$hx = eval { XML::Hash::XS->xml2hash ($xml); };
if ($@ || !$hx) {
    print STDERR "Error converting ..$! - $@\n";
    exit 1;
}

Fails

Regards, 
Deepak Khosla 
Office: 832-280-5038

**Comment by yoreek** [comment]
Try this please:
```
my $xml = "<root>
  <supportedUrls>
    <url>/xyz/</url>
    <url>/xyz/opt1=&amp;opt2=</url>
  </supportedUrls>
</root>";
$hx = eval { XML::Hash::XS->xml2hash ($xml); };
if ($@ || !$hx) {
  print STDERR "Error converting ..$! - $@\n";
  exit 1;
} 

```

**Comment by dkhosla** [comment]
Sorry for the delay Yuriy. That works.
Thanks.

Regards,
Deepak Khosla
Office: 832-280-5038
