### ISSUE TITLE
 Option for rootless xml (part 2)

### ISSUE THREAD

**Issue by darxriggs** [yoreek/XML-Hash-XS#24]
I would like to restart the discussion from #14.
So far no strong arguments have been provided against implementing this feature.

I also suggest to use `root => undef` to configure `hash2xml` to not generate an extra root element.
In case the hash does not contain exactly 1 element it might be decided to make the function fail.

Without this feature, for example the following workflow requires extra plumbing.
In addition, the generated new root element does not have attributes like the original root element might have had.
* step 1: read XML with `xml2hash` using `keep_root => 1`
* step 2: manipulate some data in the hash
* step 3: write XML with `hash2xml`

**Comment by yoreek** [comment]
I made the "keep_root" option work for generating XML.

**Comment by darxriggs** [comment]
Wow, that was fast. Thanks a lot for the quick response.

**Comment by darxriggs** [comment]
For reference, it was implemented in commit 3b2f8da9022059ec0e200251306ac64e76ddda55.
