### ISSUE TITLE
Incorrect folding of arrays in hash2xml in LX mode

### ISSUE THREAD

**Issue by nigelm** [yoreek/XML-Hash-XS#7]
The rendering of 
`    { item => [1, 2, 3]}`

in LX mode is 
`    <item>123</item>`

rather than the expected
`    <item>1</item>`
`    <item>2</item>`
`    <item>3</item>`

I realise this is a faithful rendering of Bug #83048 for `XML::Hash::LX` - https://rt.cpan.org/Public/Bug/Display.html?id=83048 - but this makes no sense in practice, and makes it impossible to round trip XML -> hash -> XML

In NATIVE mode this bug does not exist, although that mode has other issues (ie attribute handling) from my point of view.

**Comment by yoreek** [comment]
Thanks for report.
I have fixed the bug in v0.45.
Can you check, please ?

**Comment by nigelm** [comment]
Thank you for the fast fix for this - this looks like it does exactly what I would expect!

Incidentally are you intending to implement a LX mode xml2hash for this (currently I am using XML::Fast for that half of the operation)?

**Comment by yoreek** [comment]
When I get time, I'll think about it
